### ISSUE TITLE
Unexpected page counts when switching views

### ISSUE THREAD

**Issue by mtlynch** [S-anasol/siahub#10]
The page count fails to update in a sensible way when switching views (e.g. "All Hosts" to "Latest 10 hosts"). To reproduce:

1. From the "All hosts" view, scroll to page 5 in the list
1. Switch to "Latest 10 hosts" view

**Expected**: Page number changes to page 1 of 1
**Actual**: Page number changes to page 5 of 2

![image](https://cloud.githubusercontent.com/assets/7783288/25154086/21df3b7c-245d-11e7-842e-012a1a11c970.png)

It would be good if the view change caused the page number to reset and it would be good if the "Latest 10 hosts" page calculated the total number of pages as `1` instead of `2` (because there's really only one page of rows for the latest 10 hosts).

**Comment by S-anasol** [comment]
Fixed, thank you
