### ISSUE TITLE
Host contract explorer

### ISSUE THREAD

**Issue by larsfloe** [S-anasol/siahub#11]
if you want to bring value to the individual host, and in that way postiion your site comparedto siapulse I thought you should make a functinality exploring the block chain to give the host a "true" picture of their contracts - as far as i know - there is not such a function today - that would be very handy!!!

**Comment by S-anasol** [comment]
I have some thoughts about this too.
But explorer sync is really slow, so I postponed for some time such functions which require to have working explorer

**Comment by larsfloe** [comment]
hmmm I don't get you... all nodes/hosts contains a full updated ersion of the blockchain??
the issue is it is totally mumbojumbo to trace through and understand - it needs a nice structure and an interface :-)

**Comment by S-anasol** [comment]
nope, "explorer mode" need additional activation and download/prepare to use it like https://explore.sia.tech/

**Comment by S-anasol** [comment]
Blockchain doesnt contain info about host in file contract, at least until contract active.

So there is no possibility to check host's contracts, only some completed, that is sad.

Closing it for now, maybe i will return to this issue and will add some historic data to hosts.
