### ISSUE TITLE
wallet_status fails with "Too Many Requests"

### ISSUE THREAD

**Issue by mtlynch** [S-anasol/siahub#15]
The past few days, I've been seeing issues when I try to load the host explorer. It will only load one host. The console had an error about too many requests:

`app.e445cfc….js:29 GET http://siahub.info/api/wallet_status 429 (Too Many Requests)`

![image](https://cloud.githubusercontent.com/assets/7783288/26352850/93ccaf0a-3f8b-11e7-9706-3e4b6f8e9004.png)

**Comment by S-anasol** [comment]
Increased requests limit.
Should be fine now.

But strange, should be enough with default limit, maybe you have opened 2-3+ tabs? :)

**Comment by S-anasol** [comment]
fixed search to avoid "null" word in input.
