### ISSUE TITLE
Data in the graphs on the network page is not relative to each other

### ISSUE THREAD

**Issue by Fornax96** [S-anasol/siahub#19]
Having two types of data in one graph which are not related to each other is quite confusing. For example, it looks like the "active hosts" just overtook the "total hosts" in the host graph: 
![image](https://user-images.githubusercontent.com/1247928/27040297-df0c821e-4f90-11e7-9c47-349ad33eb7bf.png)
Which is actually impossible.

Same goes for the storage graph:
![image](https://user-images.githubusercontent.com/1247928/27040330-f508fce6-4f90-11e7-92ba-0c512bc5c162.png)
The graph seems to indicate that used storage has always been higher than the total storage, which is also impossible.

Just make sure that data of the same type uses the same scale in the graphs.

**Comment by S-anasol** [comment]
Different scale to make it look better.
Confusing 😞 , but look much better than same scale.

![image](https://user-images.githubusercontent.com/1709666/27044117-2d62f6a0-4fa5-11e7-90bc-38ff2ffc95a2.png)
Hosts look +/- good now, but storage flat.

But too smooth anyway, any changes almost not visible.

**Comment by Fornax96** [comment]
It does give a good impression of the massive amount of storage that's available on the network. I actually think it looks better, even if it's flat.

You could always make the graphs a bit higher, so the differences are more pronounced. 

The downside is that it takes away the usefulness of the used storage graph. Maybe that could be fixed by adding a button that hides the total storage, so the used storage takes up the full graph.

Anyway, your website, do as you please :wink:
