### ISSUE TITLE
Host list is not updating from hostdb

### ISSUE THREAD

**Issue by medisoft** [S-anasol/siahub#20]
I have a new host, and it is into the hostdb data, but is not updated on siahub, and previously it was there, but with wrong ranking.

For example, my new host is listed with rank 38 when I run siac hostdb, but it is not into the siahub site.

Yesterday I updated it and was showing in the siahub list, but with rank distinct of `siac hostdb` list.

**Comment by S-anasol** [comment]
Each sia-daemon collects own personal host stats.
So rank will be different due different collected uptime/downtime/age, for example.

> but it is not into the siahub site.
about this, with current hosts grow, default wallet refresh speed is not enough to update properly(fast enough). So scan speed about 2-3 days for all host database.
Just updated siahub wallet to handle more hosts per iteration.
Should scan all hosts for 1 day max now.

But also your host can be just unavailable due incorrect settings or something like.
If you want me to check, send your IP:PORT or public key.

**Comment by S-anasol** [comment]
hi, increased limit yesterday, now all hosts must be processed without delays.

Your host is visible now at SiaHub?
