### ISSUE TITLE
I want support SiaHub

### ISSUE THREAD

**Issue by mtlynch** [S-anasol/siahub#21]
The footer at the bottom reads "I want support SiaHub." It should read: "I want **to** support SiaHub."

![image](https://user-images.githubusercontent.com/7783288/28503846-95b65c78-6fdb-11e7-9836-773486ff74a5.png)

I would have just submitted a PR to fix this, but I couldn't find the code that controls that text in this repo. Is that stored somewhere else?

**Comment by S-anasol** [comment]
https://github.com/S-anasol/siahub/blob/master/resources/views/layouts/app.blade.php#L72

**Comment by mtlynch** [comment]
>I couldn't find the code that controls that text in this repo. Is that stored somewhere else?

Oh, whoops, I realized I forgot to sync up my fork with yours, so I was searching at 927fc7d65bddd10c7d8a77cee029e5211cf32f80 from 3 months ago.
