### ISSUE TITLE
Used storage amount appears as ~0 in graph

### ISSUE THREAD

**Issue by mtlynch** [S-anasol/siahub#22]
I love that SiaHub has these great graphs for tracking Sia network statistics. One important statistic I'd like to follow is the total amount of used storage. There's a graph that shows it, but it's graphed alongside Total Storage so it's hard to see the Used Storage:

![image](https://user-images.githubusercontent.com/7783288/28503862-ec168a34-6fdb-11e7-917e-90a3a05b8b37.png)

In the past month, total storage has nearly doubled, but you can't really see that from the graph.

Suggestion: split Total Storage and Used Storage into separate graphs. Maybe add a third graph for "Storage Utilization" that's just Used / Total.

**Comment by S-anasol** [comment]
https://github.com/S-anasol/siahub/issues/19
Changed to make it look "real" :)

And enabled legend
so it's possible to hide graphs
![image](https://user-images.githubusercontent.com/1709666/28511890-0b165460-7058-11e7-9edf-f05d39cac0ae.png)
