### ISSUE TITLE
"used_percent" progress-bar is inaccurate when at 0%.

### ISSUE THREAD

**Issue by tbenz9** [S-anasol/siahub#26]
**Actual Behavior:** In home.vue if the Used_percent column is 0% the progress-bar still shows as ~10% filled. It looks like anything from 0-10% fills the progress-bar to about 10%.  On the attached screenshot, the percent_used varies from 0-16% but all the progress-bars are filled the same amount.

**Expected Behavior:** If the Host has 0% storage used, the progress-bar should be 0% filled.  

![siahub](https://user-images.githubusercontent.com/1961202/29434454-eb81060a-8357-11e7-9cb3-925b26028433.jpeg)

**Comment by S-anasol** [comment]
This is minimal width to avoid text color changing 😆
