### ISSUE TITLE
More colors for network pie charts

### ISSUE THREAD

**Issue by betaboot** [S-anasol/siahub#28]
The pie charts on https://siahub.info/network only use green and blue. Would be great to use more colors.

**Comment by S-anasol** [comment]
thats actually should be gradient, but looks like 2 colors :D

Probably can be changed to something colorful :)

**Comment by S-anasol** [comment]
http://dsro.ru/gyazo/images/849b60cee11e7a8bf6116a9f22d7.png
http://dsro.ru/gyazo/images/257edd135949818511c33fdb837a.png
moar colors!
