### ISSUE TITLE
Network statistics have stopped updating

### ISSUE THREAD

**Issue by mtlynch** [S-anasol/siahub#31]
Looks like something broke with network stats, as it hasn't updated in a while:

![image](https://user-images.githubusercontent.com/7783288/37731276-0ab3a702-2d18-11e8-9549-7fab6a56349d.png)

**Comment by S-anasol** [comment]
Cut some RAM from SiaHub to make work another project.
Now not enough RAM to calculate network stats 😬

**Comment by S-anasol** [comment]
That part of code even dont need so much ram, just unused test calculations eat it all 😖

**Comment by S-anasol** [comment]
Fixed https://github.com/S-anasol/siahub/commit/554872af1abda486e9cada01a535649320b2c01b

**Comment by S-anasol** [comment]
Thank you @mtlynch
