### ISSUE TITLE
wish u could support an  `current_block` api 

### ISSUE THREAD

**Issue by hupengbuaa** [S-anasol/siahub#32]
I am using your api in https://explorer.siahub.info/ ,but it does not have an api accessing the current_block api.<br>
I can use the official node `/consensus` RPC get the latest block info, but it is not keep syncing from your data, sometimes the latest block isn't querable in your db.

**Comment by S-anasol** [comment]
Hi!

What kind of result you want see in this api?

Get full last block or just query latest block height?

**Comment by hupengbuaa** [comment]
The official `/consensus` RPC returns
```
WriteJSON(w, ConsensusGET{
		Synced:       api.cs.Synced(),
		Height:       api.cs.Height(),
		CurrentBlock: cbid,
		Target:       currentTarget,
		Difficulty:   currentTarget.Difficulty(),
	})
```
The height & currentBlockhash are both useful for me. My concern is the latest block's height/hash I get is also querable in your DB with `/api/hash` or `/api/height`.<br>
Wish u could help :)

**Comment by hupengbuaa** [comment]
Thanks! Really appreciate it.
