### ISSUE TITLE
Night mode update

### ISSUE THREAD

**Issue by S-anasol** [S-anasol/siahub#8]
Change some colors to make it look better :)

**Comment by Fornax96** [comment]
It's nearly impossible to read chart titles on the network page with dark mode enabled:
![image](https://user-images.githubusercontent.com/1247928/26870968-ff4e2988-4b71-11e7-85a9-ae88b6263272.png)

Could the colors be tweaked a bit?

**Comment by S-anasol** [comment]
Changed text colors for title and legend

![image](https://user-images.githubusercontent.com/1709666/26874502-8c4ff244-4b86-11e7-9842-6b459e9bb876.png)
![image](https://user-images.githubusercontent.com/1709666/26874506-8e49d3ee-4b86-11e7-943a-08951c3d2f2a.png)

**Comment by Fornax96** [comment]
Looking good!

One last remark before I shut my mouth :) Using dark blue for the wires that point at the text is not very easy to see on the dark background:
![image](https://user-images.githubusercontent.com/1247928/26876469-a8151f68-4b86-11e7-9060-17d8bac3dab5.png)

**Comment by S-anasol** [comment]
@Fornax96 i will check, probably used same(same config/unsplitable) color for background and line.

**Comment by S-anasol** [comment]
@Fornax96 done black/white

**Comment by Fornax96** [comment]
Perfect! Looks super professional now :D
